config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :cocktails, only: [:index, :show, :new, :create] do
  resources :doses, only: [:new, :create]
end
resources :doses, only: [:destroy]
root to: "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail), notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :id)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy

    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

private

  def dose_params
      params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="d-flex">
<h1 id="line_show">_____________</h1>
</div>

<h1 class="all_head">Your Cocktails</h1>

<div class="container">
  <div class="row">
    <%@cocktails.each do |cocktail| %>
      <div id="cocktail-on-index"class="col-sm-12">
      <%= cl_image_tag cocktail.photo, height: 200, width: 200, radius: 5, crop: :thumb, :class => 'img_index' %>
      <%= link_to cocktail.name, cocktail_path(cocktail), class: "btn" %>
     </div>

    <%end%>
  </div>

</div>
<div class="col-6"> <%= link_to "Create a Cocktail", new_cocktail_path %></div>

app/views/cocktails/new.html.erb
<div class="container all_head">

<h3>Give your cocktail an identity!</h3>
<p>____</p>
<br>

<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <br>
  <%= f.input :photo  %>
  <br>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Create Cocktail", class: "btn btn-primary" %>
<% end %></p>
<br>

<p>...Next up we will add some ingredients</p>

</div>
<div class="col-6"> <%= link_to "Back to Cocktails", cocktails_path %>

  </div>

app/views/cocktails/show.html.erb
<div class="d-flex">
<h1 id="line_show">_____________</h1>
</div>
<div class="container">
<div class="d-flex">
  <div class="top" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path @cocktail.photo, height: 100, width: 100, crop: :fill %>')">
    <h1><%= @cocktail.name%>
    </h1>
  </div>
</div>
<div class="col-12" width="100%" >
  <br>
  <br>

  <% @doses.each do |dose| %>
       <div class="row">
          <div class="col-5"><%= dose.description%></div>
         <div class="col-5"><%= dose.ingredient.name %></div>
         <div class="col-1"><%= link_to "X", dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %></div>
       </div>
  <% end %>
  <br>
  <br>

  </div>
  </div>
  </div>
  <div class="col-6"> <%= link_to "Add Ingredient", new_cocktail_dose_path(@cocktail) %></div>
  <div class="col-6"> <%= link_to "Back to Cocktails", cocktails_path %>

  </div>
  </div>

app/views/doses/new.html.erb
<div class="container all_head">

<h3>Add an Ingredient to <%=@cocktail.name%> recipe </h3>
<p>____</p>




<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.submit "Add to Cocktail", class: "btn btn-primary" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
        <div class="banner" id="main_banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1509669803555-fd5edd8d5a41?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
    <h1>Cocky Tails</h1>
    <p>Bespoke Cocktails for you</p>
       </div>

    <%= yield %>
     <%= javascript_include_tag "application" %>
     <%= javascript_pack_tag "application" %>
  </body>
</html>